import './globals.css'

export const metadata = {
  title: 'Weather App',
  description: 'Generated by Meet Parmar',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
